feat: support-cjs-config
CrowdStrike/monorepo-next pull request #355
Opened 2022-11-23 14:30 UTC by Exelord

Add support for CJS config file extension.

This will allow to use `monorepo-next.config.cjs` file, and will take precedence over `.js` (which can be implicitly ESM)

2022-11-23 16:46 UTC, kellyselden requested changes
Do you mind putting some detail in the commit message so it can go in the changelog?

2022-11-23 16:54 UTC, Exelord commented
I have added: `Add support for CJS config file extension`, Im thinking what kind of details should land there as well 🤔

2022-11-23 16:58 UTC, kellyselden commented
Oh I didn't see the body. That is good. I just say your commit subject "support-cjs-config" and thought that was an accidental branch name. Maybe move the body to the subject?

2022-11-29 20:11 UTC, merged

2022-11-29 20:15 UTC, kellyselden commented
Released in v9.1.0